### ISSUE TITLE
Unexpected class java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Lignum** [CCEmuX/CCEmuX#100]
Happens on startup, with Java versions 8, 9 and 10, default config.
```
CCEmuX version: 1.0.0
OS name: Linux
OS version: 4.14.43
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 10.0.1-internal
JRE architecture: 64

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:937)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:891)
	at net.clgd.ccemux.plugins.PluginManager.setup(PluginManager.java:74)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:213)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:59)
```

**Comment by SquidDev** [comment]
This is an issue with recovering from plugins which error. This occurs under OpenJDK but not OracleJDK:

```
java.lang.NoClassDefFoundError: javafx/beans/property/ReadOnlyDoubleProperty
        at net.clgd.ccemux.plugins.builtin.JFXPlugin.setup(JFXPlugin.java:60) ~[CCEmuX-cc.jar:1.0.0]
        at net.clgd.ccemux.plugins.PluginManager.setup(PluginManager.java:77) [CCEmuX-cc.jar:1.0.0]
        at net.clgd.ccemux.init.Launcher.launch(Launcher.java:213) [CCEmuX-cc.jar:1.0.0]
        at net.clgd.ccemux.init.Launcher.main(Launcher.java:59) [CCEmuX-cc.jar:1.0.0]
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.ReadOnlyDoubleProperty
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_172]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
        ... 4 more
```

I think we a) need to stop the JFX plugin from failing when it is not available and b) fix this specific issue.

**Comment by Lignum** [comment]
Works perfectly now, cheers.
