### ISSUE TITLE
Unexpected class java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by JakobDev** [CCEmuX/CCEmuX#101]
```
CCEmuX version: 1.0.0
OS name: Linux
OS version: 4.4.0-127-generic
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 1.8.0_171
JRE architecture: 64

java.lang.UnsatisfiedLinkError: no splashscreen in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.SplashScreen$1.run(SplashScreen.java:124)
	at java.awt.SplashScreen$1.run(SplashScreen.java:122)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:121)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:246)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:103)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by dmarcuse** [comment]
What arcane abomination of a Java install are you using to generate that error? Also, what OS?

**Comment by Lemmmy** [comment]
it says in the issue ape

**Comment by dmarcuse** [comment]
It says Oracle, but the only situation this should occur is with headless OpenJDK (and even then it shouldn't)

**Comment by JakobDev** [comment]
I use Ubuntu Mate 16.04 with OpenJDK

**Comment by dmarcuse** [comment]
Which OpenJDK package specifically?

**Comment by Lemmmy** [comment]
@Wilma456 Are you sure you dont' have `openjdk-8-*-headless` installed? Make sure you have a non-headless JDK installed.

**Comment by SquidDev** [comment]
Unable to reproduce on Ubuntu Mate 16.04 with the `openjdk-8-jdk` package installed. Note that this was run through a virtual machine, though it shouldn't make any difference.

**Comment by JakobDev** [comment]
I had now installed the normal openjdk-8-jre package and it works now.  The Reason was the headles-jdk. Maybe you should check this and give a error message, if the User only have the headless Version installed.

**Comment by dmarcuse** [comment]
[There is a check](https://github.com/CCEmuX/CCEmuX/blob/d5d26116ef1be0473d2edc475543ff34d8e6d88e/src/main/java/net/clgd/ccemux/init/Launcher.java#L245) for headless environments.

**Comment by JakobDev** [comment]
Then maybe your Workaround for Environments with headless is not working correct.

**Comment by SquidDev** [comment]
It's the recommended method, and part of the Java standard library. I'm honestly rather surprised it's throwing a `UnsatisfiedLinkError` rather than `HeadlessException` or something. 

I'd say this was an issue with a broken Java install, but Google seems to imply it's a relatively common issue so it's evidently "intended behaviour". Not sure what we can do to detect it really short of wrapping this all in a `try`-`catch`. It'd work, but it feels like the incorrect solution here.

**Comment by dmarcuse** [comment]
The strange part is that it reported that the environment _was not_ headless, and then promptly crashed because it is headless.
