### ISSUE TITLE
Unexpected class java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ulisesvina** [CCEmuX/CCEmuX#148]
```
CCEmuX version: 1.0.0
OS name: Linux
OS version: 5.4.0-47-generic
OS architecture: amd64
JRE vendor: Private Build
JRE version: 1.8.0_265
JRE architecture: 64

java.lang.UnsatisfiedLinkError: no splashscreen in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at java.awt.SplashScreen$1.run(SplashScreen.java:124)
	at java.awt.SplashScreen$1.run(SplashScreen.java:122)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:121)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:284)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by dmarcuse** [comment]
Could you give some context around this error?

**Comment by ulisesvina** [comment]
I couldn't run CCEmuX on Ubuntu 20.04 LTS with OpenJDK 8.

**Comment by ulisesvina** [comment]
Note: I can't give any other additional information cause I completely re-installed Ubuntu, this time with Oracle's Java 11.

**Comment by dmarcuse** [comment]
Maybe you installed a headless version of the JRE - I vaguely remember Ubuntu splitting the JRE into separate headless/graphical packages or something.

**Comment by ulisesvina** [comment]
Indeed, I installed headless JRE. Thanks.
