### ISSUE TITLE
Unexpected class java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Kolterdyx** [CCEmuX/CCEmuX#151]
```
CCEmuX version: 1.0.0
OS name: Linux
OS version: 5.9.0-2parrot1-amd64
OS architecture: amd64
JRE vendor: Debian
JRE version: 11.0.9.1
JRE architecture: 64

java.lang.UnsatisfiedLinkError: no splashscreen in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.SplashScreen$1.run(SplashScreen.java:134)
	at java.desktop/java.awt.SplashScreen$1.run(SplashScreen.java:132)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.SplashScreen.getSplashScreen(SplashScreen.java:131)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:281)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

got this error after trying to run the launcher the second time :(
I dont know what I did, or how I did it, but it crashed and gave me this error

**Comment by SquidDev** [comment]
It appears you've installed the headless JRE rather than the normal one. See #101, #148 for more details.
