### ISSUE TITLE
Symlink for "computer" directory causing crash on startup

### ISSUE THREAD

**Issue by MichelJonkman** [CCEmuX/CCEmuX#155]
I have a symlink instead of the computer directory so I can sync the folder with dropbox but the emulator crashes on startup. It works fine if I replace the folder with a symlink after it has started.

**Comment by SquidDev** [comment]
Would you be able to apply a stack trace of the crash in question?

**Comment by MichelJonkman** [comment]
`CCEmuX version: 1.0.0
OS name: Windows 10
OS version: 10.0
OS architecture: amd64
JRE vendor: AdoptOpenJDK
JRE version: 1.8.0_292
JRE architecture: 64

java.nio.file.FileAlreadyExistsException: C:\Users\mj99\AppData\Roaming\ccemux\computer
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:81)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:221)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
`

**Comment by MichelJonkman** [comment]
I have started using the --computers-dir launch parameter but it's still a bit weird.
