### ISSUE TITLE
lsUnexpected class java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by jbettaque** [CCEmuX/CCEmuX#156]
```
CCEmuX version: 1.0.0
OS name: Linux
OS version: 5.12.11-200.fc33.x86_64
OS architecture: amd64
JRE vendor: Red Hat, Inc.
JRE version: 11.0.11
JRE architecture: 64

java.nio.file.AccessDeniedException: /ccemux
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:220)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by SquidDev** [comment]
I'm _assuming_ here that we're not picking up the "application directory" and instead trying to write to the root - I've no clue why this might be the case though, cannot get this to happen on my machine.

You haven't set any of the `$XDG_*` variables to something weird have you?
