### ISSUE TITLE
Can't drag and drop files into CCEmuX

### ISSUE THREAD

**Issue by SammyForReal** [CCEmuX/CCEmuX#157]
Hello.

When i try to **import** a file via **drap and drop**, i get the following error message:
![Bildschirmfoto von 2021-08-08 21-55-15](https://user-images.githubusercontent.com/53350357/128644119-a7ec9f7c-5c36-4bd9-813d-f4cffd90450a.png)
Im currently on **linux** and try to drop the file from Nautilus _(a explorer)_.
The file has the following path: `~/.local/share/ccemux/computer/0/textbox.lua`
I also tried this with different files from different locations but that doesn't make any difference.
If it is necessary, I use **openjdk 16.0.2** as runtime environment
~ Sammy.k

**Comment by SquidDev** [comment]
```
java.nio.file.NoSuchFileException: /out.json
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
        at net.clgd.ccemux.emulation.EmulatedComputerImpl.doCopyFiles(EmulatedComputerImpl.java:190) ~[CCEmuX-cct.jar:1.0.0]
        at net.clgd.ccemux.emulation.EmulatedComputerImpl.copyFiles(EmulatedComputerImpl.java:203) ~[CCEmuX-cct.jar:1.0.0]
        at net.clgd.ccemux.rendering.awt.AWTRenderer$2.drop(AWTRenderer.java:140) ~[CCEmuX-cct.jar:1.0.0]
        at java.awt.dnd.DropTarget.drop(DropTarget.java:450) ~[?:?]
        at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:547) ~[?:?]
        at sun.awt.X11.XDropTargetContextPeer.processDropMessage(XDropTargetContextPeer.java:185) ~[?:?]
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:863) ~[?:?]
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:787) ~[?:?]
        at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:4858) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2322) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2773) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4825) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

Looks like this happens on Java 8 and Java 16.
