### ISSUE TITLE
Unexpected class java.lang.IllegalStateException when switching monitors

### ISSUE THREAD

**Issue by LinearNoodle** [CCEmuX/CCEmuX#160]
```
CCEmuX version: 1.0.0
OS name: Windows 10
OS version: 10.0
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 1.8.0_291
JRE architecture: 64

java.lang.IllegalStateException: Buffers have not been created
	at sun.awt.windows.WComponentPeer.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.updateInternalBuffers(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.revalidate(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.revalidate(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.getDrawGraphics(Unknown Source)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.renderTerminal(TerminalComponent.java:36)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:49)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:258)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.lambda$tick$0(EmulatedComputerImpl.java:179)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.tick(EmulatedComputerImpl.java:179)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$2(CCEmuX.java:178)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:176)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:205)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:337)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by SquidDev** [comment]
Possibly related to #61.

Genuinely tempted to ditch the AWT and JFX backends and look at LWJGL 3 again.

**Comment by LinearNoodle** [comment]
To clarify, this happens every single time I switch monitors (as in, completely change the display from one monitor to another, disabling the one it was previously on)
Aka when Windows forces CCEmuX to be displayed on a different monitor it crashes with that error
