### ISSUE TITLE
Unexpected class java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by RaiuTheEevee** [CCEmuX/CCEmuX#163]
When I accidentally put a space in the string for the 2nd parameter of term.blit, CCEmuX started crashing with this error.
```
CCEmuX version: 1.1.0
OS name: Windows 10
OS version: 10.0
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 17.0.1
JRE architecture: 64

java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at dan200.computercraft.core.terminal.Palette.getColour(Palette.java:48)
	at net.clgd.ccemux.api.emulation.EmulatedPalette.getColour(EmulatedPalette.java:80)
	at net.clgd.ccemux.api.rendering.PaletteAdapter.getColor(PaletteAdapter.java:84)
	at net.clgd.ccemux.rendering.awt.TerminalRenderer.drawChar(TerminalRenderer.java:70)
	at net.clgd.ccemux.rendering.awt.TerminalRenderer.render(TerminalRenderer.java:123)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.renderTerminal(TerminalComponent.java:37)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:49)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:259)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.lambda$tick$0(EmulatedComputerImpl.java:175)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.tick(EmulatedComputerImpl.java:175)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$3(CCEmuX.java:195)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:193)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:222)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:337)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by SquidDev** [comment]
And fixed! Thank you for the report!
