### ISSUE TITLE
Crash on starting CCEmuX

### ISSUE THREAD

**Issue by JetroDR** [CCEmuX/CCEmuX#164]
Today after a long time I tried to launch CCEmuX, it didn't respond at all. No UI, no error message, nothing. (even tried updating Java)
I tried to launch the last version I downloaded (50cf57ae - April 2023), this time it did give me an error.
The last version I have before that (fed1d4eb - December 2022) does work. Upon launching this version downloaded the latest version (989cfe52) but unfortunately this one also crashes while launching.
![CCEmuX Error](https://github.com/CCEmuX/CCEmuX/assets/102870049/263d2666-35ce-4f1e-b39f-b27375b49c4b)

**Comment by SquidDev** [comment]
Oh, this is very odd. Can you run CCEmuX from the command line instead and paste the log here?

**Comment by JetroDR** [comment]
So I ran both the CCEmuX launcher and the specific version that doesn't work and they both came up with the same error.
<details><summary>Log</summary>

```
Starting CCEmuX launcher
Emulator version: EmuVersion(hash=989cfe52, build=cct)
Emulator main class: net.clgd.ccemux.init.Launcher
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/clgd/ccemux/init/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at cc.emux.launcher.Launcher.main(Launcher.kt:100)
```

</details>

**Comment by SquidDev** [comment]
Ahh, it looks like you're running Java 8, but recent versions of CC:T (and thus CCEmuX) require Java 17. You said you tried updating Java recently, so it might be worth double checking that Java 17 is the default.

**Comment by JetroDR** [comment]
I just double checked I updated to the latest update of version 8. I didn't know there where multiple version of Java. Installed Java 20 and now it works again!
Thanks for the help.

**Comment by SquidDev** [comment]
Lovely, glad it's working :)
