### ISSUE TITLE
Unexpected class java.lang.IllegalStateException

### ISSUE THREAD

**Issue by 12354fdw** [CCEmuX/CCEmuX#169]
```
CCEmuX version: 1.1.0
OS name: Mac OS X
OS version: 10.14.6
OS architecture: x86_64
JRE vendor: Oracle Corporation
JRE version: 20.0.2
JRE architecture: 64

java.lang.IllegalStateException: Component must have a valid peer
	at java.desktop/java.awt.Component$FlipBufferStrategy.flip(Component.java:4170)
	at java.desktop/java.awt.Component$FlipBufferStrategy.show(Component.java:4297)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:52)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:257)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.lambda$tick$0(EmulatedComputerImpl.java:197)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.tick(EmulatedComputerImpl.java:197)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$2(CCEmuX.java:193)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:191)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:220)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:337)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:117)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:102)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:102)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by 12354fdw** [comment]
note: it displayed this when i was closing computer 0 and 1.

**Comment by SquidDev** [comment]
Thanks for the report! This looks to be the same issue as #61. I'm afraid I've never been able to reproduce this — I think this involves a race condition, and so it happens very rarely.
