### ISSUE TITLE
NPE when using term.blit with invalid colors

### ISSUE THREAD

**Issue by viluon** [CCEmuX/CCEmuX#66]
Whoops :confused: 
```
OS name: Linux
OS version: 3.16.0-4-amd64
OS architecture: amd64

JRE vendor: Oracle Corporation
JRE version: 1.8.0_111
JRE architecture: 64

Stack trace: java.lang.NullPointerException
	at net.clgd.ccemux.Utils.clampColor(Utils.java:26)
	at net.clgd.ccemux.rendering.PaletteCacher.getColor(PaletteCacher.java:36)
	at net.clgd.ccemux.rendering.PaletteCacher.getColor(PaletteCacher.java:32)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.renderTerminal(TerminalComponent.java:89)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:124)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:164)
	at net.clgd.ccemux.emulation.EmulatedComputer.lambda$advance$0(EmulatedComputer.java:161)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at net.clgd.ccemux.emulation.EmulatedComputer.advance(EmulatedComputer.java:161)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$0(CCEmuX.java:125)
	at java.util.HashMap$KeySet.forEach(HashMap.java:932)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:123)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:148)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:88)
```

**Comment by dmarcuse** [comment]
What were you doing before the crash?

**Comment by viluon** [comment]
`string.char( unpack( loooong_array ) )`, I suppose. Can't test now, but will ASAP.

**Comment by Lustyn** [comment]
This has something to do with you setting invalid palette colors. I have tried to fix this same issue multiple times, but could never get a proper fix.

**Comment by viluon** [comment]
Definitely not, I wasn't modifying the palette at all @justync7 

It doesn't seem to originate from `string.char`ing, further investigation underway.

**Comment by viluon** [comment]
Replicated, simplifying to minimal reproduction code...

**EDIT**: Damn it, guys, your IO is being lazy. Logfile ends mid-write.
**EDIT2**: I'm giving up...
```
test_doubles.lua:6: === Test started ===
init.lua:2765: new_from_points
init.lua:2786: prefilling
init.lua:2819: ready to be served!
init.lua:2765: new_from_points
init.lua:2786: prefilling
init.lua:2819: ready to be served!
init.lua:649: render_to_window
init.lua:930: cookery!
init.lua:978: line	0
init.lua:988: x	0
init.lua:992: 	pixel breakdown triggered
init.lua:1002:   last_pixel	15.032
init.lua:1004: background	table: c03d763
init.lua:1005: foreground	table: 31ce0d
init.lua:1007: please wor
```
[`/symlink/desktox/buffer/init.lua`](https://pastebin.com/NfeAsbVU), [`/symlink/desktox/buffer/tests/test_doubles.lua`](https://pastebin.com/nbz0mqU2). Uses a custom `require()`, so you might need to edit some parts in order to get it ~~working~~ crashing.

Best luck to ya.

**EDIT3**: Oh and the logfile is then in `/symlink/desktox/log.txt`. I tried to force flushing with every `log()` call, which makes the test hang for some time. The emu crashes pretty much instantly with logging disabled.

**Comment by viluon** [comment]
Found the issue.
![screenshot from 2017-07-06 10-23-12](https://user-images.githubusercontent.com/7235381/27902209-2f98e2ca-6235-11e7-8229-27eed05da8a5.png)
Shortly after editing the last comment, I realised I can place an error call and move it around in the file to track where does normal execution stop (yeah, dumb me for not realising this sooner). The logfile was seriously out of sync.

**Comment by dmarcuse** [comment]
Can confirm this, even happens on the `master` branch although a different exception is produced:

```OS name: Linux
OS version: 4.11.6-1-zen
OS architecture: amd64

JRE vendor: Oracle Corporation
JRE version: 1.8.0_131
JRE architecture: 64

Stack trace: java.lang.ArrayIndexOutOfBoundsException: -1
	at net.clgd.ccemux.rendering.awt.TerminalComponent.drawChar(TerminalComponent.java:52)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.renderTerminal(TerminalComponent.java:86)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:114)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:164)
	at net.clgd.ccemux.emulation.EmulatedComputer.lambda$advance$0(EmulatedComputer.java:161)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at net.clgd.ccemux.emulation.EmulatedComputer.advance(EmulatedComputer.java:161)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$0(CCEmuX.java:125)
	at java.util.HashMap$KeySet.forEach(HashMap.java:932)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:123)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:148)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:86)
```

**Comment by viluon** [comment]
Thanks @apemanzilla
